### ISSUE TITLE
seems nobody update this repo

### ISSUE THREAD

**Issue by ardawan** [dhowden/raspicam#1]
I just test the package and realised that the latest commit was about 5 years ago.
wondering if still someone cares about this repo to bring some more features ?

**Comment by dhowden** [comment]
Hey!  Most of the original raspicam features are already implemented (and it works) so there hasn't been much need to change anything.  Happy to accept contributions if there are new things to support.

**Comment by ardawan** [comment]
Actually I’m looking for a package for taking video and use it for streaming. 

I couldn’t find any example about video in your library.

Could you pls show me if your package supports ?

**Comment by dhowden** [comment]
Yes, you need to use the Vid variant of types (as opposed to the `Still` ones): https://godoc.org/github.com/dhowden/raspicam#Vid
